version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - contactos-network

  api:
    build: .
    container_name: gestion-contactos-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/contactsDB
    depends_on:
      - mongodb
    networks:
      - contactos-network

volumes:
  mongodb_data:

networks:
  contactos-network:
    driver: bridge